### ISSUE TITLE
超过预定人数视觉提示

### ISSUE THREAD

**Issue by qllokirin** [2ndelement/nwpu-lesson-select-enhance#1]
非常好用，直接火速一手star

请问可以把超过预定人数的课提前或者把数字变个颜色吗

**Comment by 2ndelement** [comment]
> 非常好用，直接火速一手star
> 
> 请问可以把超过预定人数的课提前或者把数字变个颜色吗

将在v0.3 版本添加颜色指示

**Comment by 2ndelement** [comment]
已经发布相应版本

**Comment by qllokirin** [comment]
> 已经发布相应版本

tql 已经用上了
