### ISSUE TITLE
建议使用另一个 API 获取人数

### ISSUE THREAD

**Issue by Nikaidou-Shinku** [2ndelement/nwpu-lesson-select-enhance#3]
- 考虑使用 `https://jwxt.nwpu.edu.cn/course-selection-api/api/v1/student/course-select/std-count` 替代现在这个 API，现在这个直接阻塞掉了。
- 以及考虑使用 `fetch` 替代裸 XHR。

**Comment by 2ndelement** [comment]
> * 考虑使用 `https://jwxt.nwpu.edu.cn/course-selection-api/api/v1/student/course-select/std-count` 替代现在这个 API，现在这个直接阻塞掉了。
> * 以及考虑使用 `fetch` 替代裸 XHR。

- 请问该api的参数`https://jwxt.nwpu.edu.cn/course-selection-api/api/v1/student/course-select/std-count` ,目前我无法访问该api.

**Comment by 2ndelement** [comment]
> * 考虑使用 `https://jwxt.nwpu.edu.cn/course-selection-api/api/v1/student/course-select/std-count` 替代现在这个 API，现在这个直接阻塞掉了。
> * 以及考虑使用 `fetch` 替代裸 XHR。

将使用新API完成逻辑,感谢指导

**Comment by 2ndelement** [comment]
> * 考虑使用 `https://jwxt.nwpu.edu.cn/course-selection-api/api/v1/student/course-select/std-count` 替代现在这个 API，现在这个直接阻塞掉了。
> * 以及考虑使用 `fetch` 替代裸 XHR。

在 [v0.4](https://greasyfork.org/zh-CN/scripts/449714-%E7%BF%B1%E7%BF%94%E9%97%A8%E6%88%B7%E9%80%89%E8%AF%BE%E5%A2%9E%E5%BC%BA) 中已经采用了新的API并使用 `fetch` 进行请求, ~~现学的fetch(~~
